### ISSUE TITLE
README INSTRUCTION problem

### ISSUE THREAD

**Issue by hiepxanh** [cedvdb/ng2share#1]
in your instruction you are using: 
`[properties]='{title:'my title', description:'my desc', img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}'`
but the truth is it must use double quote mark like this.
`[properties]="{title:'my title', description:'my desc', img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}"`
please fix this. this take me 10 minute to try, understand and use that feature. 
and otherwise, your component is wonderful. thanks you alot. it save me a lot of time

**Comment by cedvdb** [comment]
Thanks for the head's up, I've been busy lately, Ence my late reply. I'm gonna fix it.

By the way, if you are using the angular-cli they intend the static assets to be in the assets folder. I forgot to mention that in the readme.

**Comment by cedvdb** [comment]
@hiepxanh I changed some things as someone mentioned there was a bug. If you are still using it you should definitely update.

**Comment by whitebyte** [comment]
Currently none of the above versions doesn't work and leads to parsing erros. Even something as simple as `[properties]="{ title: 'test', description: 'test', img: 'test' }",` doesn't want to compile.

**Comment by cedvdb** [comment]
@whitebyte I've too much on my plate at the moment to check this out, maybe try another lib or submit a PR. I'll get back on this in a few weeks, right now I'm too busy with my job.
