### ISSUE TITLE
Customising the ng2share component

### ISSUE THREAD

**Issue by VishalGulati** [cedvdb/ng2share#2]
I used this component and it worked great. I was however confused about how to customize the content being shared. I tried by manually setting the value of `this.properties.url` to some static url inside function `fetchProperties` in `share-container.component.ts` file. It worked. However if the length of url string is large then it trims the url to 50 character length and tries to share that link which gives 404. Is this a genuine issue or I am missing something? Also how to customize the component to share content based on location where user has clicked on any of these sharing buttons. Please suggest!

**Comment by VishalGulati** [comment]
Also how to check if the share on Facebook was successful or not.

**Comment by cedvdb** [comment]
@VishalGulati Thank you and sorry for the late reply.

I did indeed forget to encode the url (so if you had params, those were cut). Thank you.
 I did it now so it should be fixed, I really didn't test it much though as I'm short on time. 

I'm gonna push it to git any sec. If there is still any problem feel free to tell me and I'll fix it. 

as for customizing the sharers, you can use the input properties for that as in the readme.

By the way, now it uses font awesome so if you are still using it you might want to check the installation step.
