### ISSUE TITLE
Need support to send dynamic URL, TITLE and DESCRIPTION from directive

### ISSUE THREAD

**Issue by chandregowda** [cedvdb/ng2share#5]
Thanks for this nice Module.
I would like to pass customized **url, title and description and image** dynamically.

Initially I tried by passing object like
`properties={title:'my title', description:'my desc',img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}`
It was throwing error in browser 'Template parsing error'

Then I modified your code to accept string and then convert it to JSON object like
                  `[properties]='{"url":"my url", "title":"my title", "description":"my desc","img":"an image", "via":"Ced_VDB", "hashtags":"someHashTag"}'`
and updated **fetchProperties** function in **share-container.components.ts**
```
if (typeof(this.properties) === 'string'){
      this.properties = JSON.parse(this.properties);
    }
```
Is this the right aproach, if not please update your document with a sample example.

**Comment by cedvdb** [comment]
@chandregowda 

Your first try is invalid in angular. You have to use this:

`[properties]="{title:'my title', description:'my desc',img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}"` 

You did this:

`properties={title:'my title', description:'my desc',img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}` (<= invalid angular)

when you don't use the `[]` then the value is coerced to a string. Furthermore you always need to surround your attribute values with a string delimiter `"{name: 'ced'}"`.

I'm closing this for now, feel free to reply if it was just a typo in your question I'll investigate.

**Comment by chandregowda** [comment]
Thanks for the reply, actually I tried that format not sure if I surrounded properties with [ and ] when using `="{title:'my title', description:'my desc',img:' an image', via:'Ced_VDB', hashtags:'someHashTag'}"`

It is working fine now.
